version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'vacancies'
    ports:
      - '3306:3306'
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_ARBITRARY: '1'
    depends_on:
      - db
    networks:
      - app-network

  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    ports:
      - '8000:8000'
    networks:
      - app-network
    depends_on:
      - db

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - fastapi

networks:
  app-network:
    driver: bridge